### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by macpli** [macpli/etch-a-sketch#1]
- [x] Redo core logic
- [x] Add grid size choice
- [x] Make grid fixed size
- [x] Revamp the style
- [x] Add eraser
- [x] Add logic to erase button
- [x] Add color choice
- [x] Add coloring function
